import {logError} from '../utils/logError'
import sleep from '../utils/sleep'


export class CommentBox {
  static resizeToFitContent(textarea: HTMLInputElement): void {
    textarea.style.height = 'auto'
    textarea.style.height = textarea.scrollHeight + 'px'
  }

  static async getCommentBox(): Promise<HTMLInputElement> {
    const commentBox = document.querySelector('.textfield')
    let inputFieldParent = document.querySelector('[data-on-mouseup="App.Controller.Comment.handleOnMouseUp"]') as HTMLInputElement
    if (commentBox && !inputFieldParent) {
      // @ts-expect-error - Click definitely works here, no idea why it's complaining
      commentBox.click()
      await sleep(100)
      inputFieldParent = document.querySelector('[data-on-mouseup="App.Controller.Comment.handleOnMouseUp"]') as HTMLInputElement
    }
    return inputFieldParent
  }

  static async populate(text: string): Promise<void> {
    if (text === undefined) {
      return
    }

    const commentBox = await this.getCommentBox() as HTMLInputElement
    const content = '✨ Generated by Story Readiness Assistant GPT ✨\n\n'
    if (!commentBox.value.includes(content)) {
      commentBox.value = content
    }
    commentBox.value = commentBox.value + text
    this.resizeToFitContent(commentBox)
  }

  static async clear() {
    const commentBox = await this.getCommentBox()
    commentBox.value = ''
    this.resizeToFitContent(commentBox)
  }
}


chrome.runtime.onMessage.addListener((request) => {
  if (request.type === 'updateOpenAiResponse') {
    if (request.data !== undefined) {
      CommentBox.populate(request.data).catch(logError)
    }
  }
  if (request.type === 'OpenAIResponseFailed') {
    CommentBox.clear().catch(logError)
  }
})
