import {logError, sleep} from '../utils/utils'

function extractStoryDescription(){
    const descriptionDiv = document.querySelector('[data-key="description"]')
    return descriptionDiv.textContent
}

function resizeTextareaToFitContent(textarea){
    textarea.style.height = 'auto'
    textarea.style.height = textarea.scrollHeight + 'px'
}

async function getCommentBox(){
    const commentBox = document.querySelector('.textfield')
    let inputFieldParent = document.querySelector('[data-on-mouseup="App.Controller.Comment.handleOnMouseUp"]')
    if (commentBox && !inputFieldParent) {
        commentBox.click()
        await sleep(100)
        inputFieldParent = document.querySelector('[data-on-mouseup="App.Controller.Comment.handleOnMouseUp"]')
    }
    const content = '✨ Generated by Story Readiness Assistant GPT ✨\n\n'
    if (!inputFieldParent.value.includes(content)) {
        inputFieldParent.value = content
    }
    return inputFieldParent
}

async function populateCommentBox(response){
    if (response === undefined) {
        return
    }
    const inputFieldParent = await getCommentBox()
    inputFieldParent.value = inputFieldParent.value + response
    resizeTextareaToFitContent(inputFieldParent)
}

async function clearCommentBox(){
    const inputFieldParent = await getCommentBox()
    inputFieldParent.value = ''
    resizeTextareaToFitContent(inputFieldParent)
}

export async function analyzeStoryDescription(activeTabUrl){
    if (activeTabUrl.includes('story')) {
        const description = extractStoryDescription()
        const response = await chrome.runtime.sendMessage({
            action: 'callOpenAI',
            data: {prompt: description}
        })
        populateCommentBox(response.data).catch(logError)
    }
}

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.message === 'updateOpenAiResponse') {
        if (request.data !== undefined) {
            populateCommentBox(request.data).catch(logError)
        }
    }
    if (request.message === 'OpenAIResponseFailed') {
        clearCommentBox().catch(logError)
    }
})